apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
      - name: server
        image: server:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
