apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: server
  name: server
  selfLink: /api/v1/namespaces/default/services/server
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
