apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: server-node
  name: server-node
  selfLink: /api/v1/namespaces/default/services/server-node
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: server-node
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
