apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bot
  name: bot
  selfLink: /api/v1/namespaces/default/services/bot
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bot
  name: bot
  selfLink: /api/v1/namespaces/default/services/bot
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
