apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
        version: v1
    spec:
      containers:
      - name: bot
        image: bot:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
