apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bot
        version: v2
    spec:
      containers:
      - name: bot
        image: bot:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
